### ISSUE TITLE
Brick count matching Replica count

### ISSUE THREAD

**Issue by tpowell-rms** [biola/chef-gluster#4]
From: https://github.com/biola/chef-gluster/blob/master/recipes/server_setup.rb#L111
```
if brick_count != volume_values['replica_count']
```

We have a scenario where we have more bricks than we want replicas. For example, we may have a 10 brick cluster. But we may only care about replicating the data 3 times. 

With the above code setup, they always have to be equal. Is this intended behavior? 

I am thinking something like this should be good...
```
if brick_count < volume_values['replica_count']
```

**Comment by jared-k** [comment]
The code was originally intended for a two-node cluster and didn't take more complex scenarios into consideration. But I agree, that should be a suitable fix. I'll roll that in after running some tests.
